import os
import time

os.system('cls')

def loading_icon(loop):
    for i in range(loop):
        os.system('cls')
        print("|")
        time.sleep(.05)
        os.system('cls')
        print("/")
        time.sleep(.05)
        os.system('cls')
        print("-")
        time.sleep(.05)
        os.system('cls')
        print("\\")
        time.sleep(.05)
        os.system('cls')

def startup_logo():
    os.system('cls')
    print("-")
    time.sleep(.01)
    os.system('cls')
    print("--")
    time.sleep(.01)
    os.system('cls')
    print("---")
    time.sleep(.01)
    os.system('cls')
    print("----")
    time.sleep(.01)
    os.system('cls')
    print("---- ")
    time.sleep(.01)
    os.system('cls')
    print("---- -")
    time.sleep(.01)
    os.system('cls')
    print("---- --")
    time.sleep(.01)
    os.system('cls')
    print("---- ---")
    time.sleep(.5)
    os.system('cls')
    print("_--- ---")
    time.sleep(.01)
    os.system('cls')
    print("W_-- ---")
    time.sleep(.01)
    os.system('cls')
    print("Wi_- ---")
    time.sleep(.01)
    os.system('cls')
    print("Wis_ ---")
    time.sleep(.01)
    os.system('cls')
    print("Wisp ---")
    time.sleep(.01)
    os.system('cls')
    print("Wisp _--")
    time.sleep(.01)
    os.system('cls')
    print("Wisp D_-")
    time.sleep(.01)
    os.system('cls')
    print("Wisp De_")
    time.sleep(.01)
    os.system('cls')
    print("Wisp Dex")
    time.sleep(1)
    os.system('cls')

loading_icon(1)
startup_logo()